---
- hosts: all
  sudo: yes
  vars:
   - version: 1.5.1
  tasks:
   - name: Install Elasticsearch
     script: scripts/install-elasticsearch.sh {{version}} creates=/etc/elasticsearch/elasticsearch.yml

   - name: Configure Elasticsearch
     template: src=files/elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml

   - name: Start Elasticsearch
     service: name=elasticsearch state=started

   - name: Configure Firewall for Elasticsearch
     shell: iptables -A INPUT -s 127.0.0.1 -p tcp --destination-port 9200 -m state --state NEW,ESTABLISHED -j ACCEPT


