---
- hosts: all
  sudo: yes
  vars:
   - config: files/mongodb.conf
  tasks:
   - name: Install Mongodb
     shell: apt-get install -y mongodb creates=/usr/bin/mongod
     notify:
      - Start Mongodb

   - name: Configure Mongodb
     copy: src={{config}} dest=/etc/mongodb.conf
     notify:
      - Reload Mongodb

   - name: Configure Firewall for Mongodb
     shell: iptables -A INPUT -s 127.0.0.1 -p tcp --destination-port 27017 -m state --state NEW,ESTABLISHED -j ACCEPT


  handlers:
    - name: Start Mongodb
      service: name=mongodb state=started

    - name: Reload Mongodb
      service: name=mongodb state=reloaded
