---
- hosts: all
  sudo: yes
  tasks:
  - name: Install Python Fundamentals
    apt: pkg={{ item }} state=installed
    with_items:
      - python-dev
      - python-pip
      - python-virtualenv
      - python3
      - python3-pip
